spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.sql.init.mode=never
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

CLOUD_NAME=test-cloud
CLOUD_API=test-api-key
CLOUD_SECRET=test-secret
EMAIL=test@example.com
EMPASS=test-password
FRONTEND_URL=http://localhost:3000
FRONTEND_URL_RESET=http://localhost:3000/reset-password
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=test@example.com
spring.mail.password=test-password
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
cloudinary.cloud-name=test-cloud
cloudinary.api-key=test-api-key
cloudinary.api-secret=test-api-secret