spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URLCB:jdbc:postgresql://localhost:5432/cBuilder}
spring.datasource.username=${DB_USERNAMECB:postgres}
spring.datasource.password=${DB_PASSWORDCB:Drake@7890}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
