spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URLCB}
spring.datasource.username=${DB_USERNAMECB}
spring.datasource.password=${DB_PASSWORDCB}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect